### ISSUE TITLE
Call to undefined function App\add_filter() in advanced-custom-fields.php:20

### ISSUE THREAD

**Issue by yaaax** [MWDelaney/sage-advanced-custom-fields#2]
When installing from my theme directory,
`$ composer require "mwdelaney/sage-advanced-custom-fields"`

I get this error:
```
Using version ^1.3 for mwdelaney/sage-advanced-custom-fields
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing mwdelaney/sage-advanced-custom-fields (1.3): Loading from cache
Writing lock file
Generating autoload files

PHP Fatal error:  Uncaught Error: Call to undefined function App\add_filter() in
[MY_THEME_PATH]/vendor/mwdelaney/sage-advanced-custom-fields/advanced-custom-fields.php:20
```

Stack trace:
```
Stack trace:
#0 [MY_THEME_PATH]/vendor/composer/autoload_real.php(66): require()
#1 [MY_THEME_PATH]/vendor/composer/autoload_real.php(56): composerRequire0bc18edeeeed9e9bf8f490ac6c7e5356('d28648b76004e76...', '/Users/yaaax/...')
#2 [MY_THEME_PATH]/vendor/autoload.php(7): ComposerAutoloaderInit0bc18edeeeed9e9bf8f490ac6c7e5356::getLoader()
#3 [MY_THEME_PATH]/vendor/kylekatarnls/update-helper/src/UpdateHelper/UpdateHelper.php(78): include_once('/Users/yaaax/...')
#4 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(195) : eval()'d code(31): UpdateHelper\UpdateHelper::check(Object(Composer\Script\E in [MY_THEME_PATH]/vendor/mwdelaney/sage-advanced-custom-fields/advanced-custom-fields.php on line 20
```

**Comment by MWDelaney** [comment]
This should be fixed by be772a49cf8cc0e88a65d2ad718f8189e3e1ce89

I released version 1.4 with this fix. Let me know if this (or any other problem) persists.

**Comment by MikaCaldera** [comment]
@MWDelaney I ran composer update and got another error. 

`"mwdelaney/sage-advanced-custom-fields": "^1.4",`

```Fatal error: Uncaught Error: Call to undefined function add_filter() in /themes/projects/vendor/mwdelaney/sage-advanced-custom-fie
lds/advanced-custom-fields.php:18
Stack trace:
#0 /themes/projects/vendor/composer/autoload_real.php(66): require()
#1 /themes/projects/vendor/composer/autoload_real.php(56): composerRequired90e6d046f370b0953fec4ff2146463e('d28648b76004e76...', '/Users/...')
#2 /themes/projects/vendor/autoload.php(7): ComposerAutoloaderInitd90e6d046f370b0953fec4ff2146463e::getLoader()
#3 /themes/projects/vendor/kylekatarnls/update-helper/src/UpdateHelper/UpdateHelper.php(78): include_once('/Users/mikacald...')
#4 /web/app/the in /themes/projects/vendor/mwdelaney/sage-advanced-custom-fields/advanced-custom-fields.php on line 18````

**Comment by MikaCaldera** [comment]
All set! Gracias!

**Comment by yaaax** [comment]
All good thanks
